name: 'chatgpt-action'
description: 'A collection of ChatGPT assistants, e.g., code viewer, labeler, assigner, etc.'
author: 'Joshua Schmid'
inputs:
  action:
    type: string
    required: false
    description: 'The action to run, currently can be only "review"'
    default: 'review'
  debug:
    type: boolean
    required: false
    description: 'Enable debug mode'
    default: false
  path_filters:
    type: string
    required: false
    description: |
      The path filters, e.g., "src/**.py", "!dist/**", each line will be considered as one pattern.
      See also

      - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
      - https://github.com/isaacs/minimatch
    default: |
      !dist/**
      **/package-lock.json
  review_comment_lgtm:
    type: boolean
    required: false
    description: 'Leave comments even the patch is LGTM'
    default: false
  review_beginning:
    type: string
    required: false
    description: "The beginning prompt of a code review dialog"
    default: |
      Hi ChatGPT, I have a pull request with title "$title" and the description is as follows,

      > $description.

      Next, I will given you a series of patches, each of them consists of a filename and a diff
      snippet, and you need to do a brief code review for every message, and tell me improvement suggestion.
      If the patch is looks good and acceptable, please reply "LGTM!" with a short comment.

      You answer should be concise. Don't include the diff in your comment, and markdown format is
      preferred. Reply "OK" to confirm.
  review_patch:
    type: string
    required: false
    description: 'The prompt for each chunks/patches'
    default: |
      $filename

      ```diff
      $patch
      ```
  custom_prompt_path:
    type: string
    required: false
    description: 'A custom prompt sourced from a file'
runs:
  using: 'node20'
  main: 'dist/index.js'
